[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[theme]
primaryColor = '#006d77'
backgroundColor = '#f8fafc'
secondaryBackgroundColor = '#ffffff'
textColor = '#0f172a'
font = 'sans serif'

[browser]
gatherUsageStats = false
